### ISSUE TITLE
Document How to Install on Existing OP25

### ISSUE THREAD

**Issue by SenorFusion** [SarahRoseLives/OP25MCH#2]
First - thank you for the awesome project! 

I'm excited to try it but I have an existing OP25 install that is working great (and other things running on the pi too)

Would it be possible to post the installation steps for running MCH on an existing OP25?

Looking at the newinstall script, is it as simple as running the op25_mchserver.py as a systemd service and then running the android app and then setting the android app to view my existing install?

I saw the "view-only" Android version, but being able to use the features on the full version would be great!

Thanks!

**Comment by SarahRoseLives** [comment]
The android release is available in this repo, the install script will not work with an existing OP25 installation.
Technically you could manually setup the hotspot and op25_mchserver.py but I don't currently have a write up for that.

Plus integrating with an existing install could cause unknown issues as my software expects the environment that my script provides.

You'd also have to set up a service that points to the right location which creates more potential issues when deviating from my installation.

I can look into supporting existing installs at some point but currently the recommendation is to run the script from a fresh install.
