### ISSUE TITLE
Workarounds for x86_64 VM

### ISSUE THREAD

**Issue by danleeper80** [SarahRoseLives/OP25MCH#3]
Hi, thanks for the cool project I was successfully able to run your project under a Debian Bookworm x86_64 VM (my Pi died recently) running in Proxmox 8.1.4 aka KVM. However, there are several hard-coded items to the average user not using a Raspberry Pi would encounter. If variables could be added to the script ideally as prompts will be a good enhancement it will make other platforms possible ie, Bare Metal, VMs or SBCs that are not the Pi. Containerizing as a Docker image something else to consider.

Changes / issues corrected to run in my VM:
- External Ethernet interface hard coded as eth0 (iptables forwarding configuration) changed to enp6s18 for my VM interface name differs depending on Hypervisor and/or Ethernet adapter being used
- WiFi (hostapd.conf and dhcpd.conf) Interface hard coded as wlan0 changed to wlx74da381ca2e2 for my Edimax EW-7711MAC 802.11ac USB adapter 
- WiFi (hostapd.conf) only accommodates for 2.5ghz channel 7 as hard coded changed to hw_mode=a and channel=36 for 5GHz
- WiFi (hostapd.conf) does not specify country_code= prevents use of 5GHz channels

**Comment by SarahRoseLives** [comment]
I'm not opposed to this however the idea is to make it as simple for a user to install as possible.
I worry that some users might get confused trying to find these details on their own in a script where they must specific interfaces and such.

If a script can be created that works without adding complications I'm all ears.
The other issue is that I've only a raspi to test on.
